----------------------------------------------------------------------------------------------------------
-- LIMPIEZA OPCIONAL DE TABLAS Y OBJETOS EXISTENTES
----------------------------------------------------------------------------------------------------------

-- Procedimientos y funciones (si no existen, ignora el error)

-- CARRERA
DROP PROCEDURE insertarCarrera;
DROP PROCEDURE modificarCarrera;
DROP PROCEDURE eliminarCarrera;
DROP FUNCTION listarCarreras;
DROP FUNCTION buscarCarreraPorCodigo;
DROP FUNCTION buscarCarreraPorNombre;

-- CURSO
DROP PROCEDURE insertarCurso;
DROP PROCEDURE modificarCurso;
DROP PROCEDURE eliminarCurso;
DROP FUNCTION listarCursos;
DROP FUNCTION buscarCursoPorNombre;
DROP FUNCTION buscarCursoPorCodigo;
DROP FUNCTION buscarCursosPorCarrera;

-- CICLO
DROP PROCEDURE insertarCiclo;
DROP PROCEDURE modificarCiclo;
DROP PROCEDURE eliminarCiclo;
DROP FUNCTION listarCiclos;
DROP FUNCTION buscarCicloPorAnnio;
DROP PROCEDURE activarCiclo;

-- CARRERA_CURSO
DROP PROCEDURE insertarCursoACarrera;
DROP PROCEDURE eliminarCursoDeCarrera;
DROP PROCEDURE modificarOrdenCursoCarrera;
DROP FUNCTION buscarCursosPorCarreraYCiclo;
DROP FUNCTION listarCarreraCurso;

-- PROFESOR
DROP PROCEDURE insertarProfesor;
DROP PROCEDURE modificarProfesor;
DROP PROCEDURE eliminarProfesor;
DROP FUNCTION listarProfesores;
DROP FUNCTION buscarProfesorPorCedula;
DROP FUNCTION buscarProfesorPorNombre;

-- ALUMNO
DROP PROCEDURE insertarAlumno;
DROP PROCEDURE modificarAlumno;
DROP PROCEDURE eliminarAlumno;
DROP FUNCTION listarAlumnos;
DROP FUNCTION buscarAlumnoPorCedula;
DROP FUNCTION buscarAlumnoPorNombre;
DROP FUNCTION buscarAlumnosPorCarrera;

-- GRUPO
DROP PROCEDURE insertarGrupo;
DROP PROCEDURE modificarGrupo;
DROP PROCEDURE eliminarGrupo;
DROP FUNCTION listarGrupos;
DROP FUNCTION buscarGruposPorCarreraCurso;

-- MATRICULA
DROP PROCEDURE insertarMatricula;
DROP PROCEDURE modificarMatricula;
DROP PROCEDURE eliminarMatricula;
DROP PROCEDURE listarMatriculasPorAlumno;
DROP PROCEDURE listarMatriculasPorAlumnoYCiclo;

-- USUARIO
DROP PROCEDURE insertarUsuario;
DROP PROCEDURE modificarUsuario;
DROP PROCEDURE eliminarUsuario;
DROP FUNCTION listarUsuarios;
DROP FUNCTION buscarUsuarioPorCedula;
DROP PROCEDURE loginUsuario;

-- Package
DROP PACKAGE Types;

-- Tablas
DROP TABLE Matricula CASCADE CONSTRAINTS;
DROP TABLE Grupo CASCADE CONSTRAINTS;
DROP TABLE Alumno CASCADE CONSTRAINTS;
DROP TABLE Profesor CASCADE CONSTRAINTS;
DROP TABLE Carrera_Curso CASCADE CONSTRAINTS;
DROP TABLE Ciclo CASCADE CONSTRAINTS;
DROP TABLE Curso CASCADE CONSTRAINTS;
DROP TABLE Carrera CASCADE CONSTRAINTS;
DROP TABLE Usuario CASCADE CONSTRAINTS;

COMMIT;

----------------------------------------------------------------------------------------------------------
-- CREACIÓN DE ESTRUCTURA DE BASE DE DATOS (TABLAS Y OBJETOS PL/SQL)
----------------------------------------------------------------------------------------------------------

-- TABLAS

CREATE TABLE Carrera (
    id_carrera NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(10) UNIQUE,
    nombre VARCHAR2(100),
    titulo VARCHAR2(100)
);

CREATE TABLE Curso (
    id_curso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(10) UNIQUE,
    nombre VARCHAR2(100),
    creditos NUMBER,
    horas_semanales NUMBER
);

CREATE TABLE Ciclo (
    id_ciclo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio NUMBER,
    numero NUMBER,
    fecha_inicio DATE,
    fecha_fin DATE,
    estado VARCHAR2(10)
);

CREATE TABLE Carrera_Curso (
    id_carrera_curso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pk_carrera NUMBER,
    pk_curso NUMBER,
    pk_ciclo NUMBER,
    FOREIGN KEY (pk_carrera) REFERENCES Carrera(id_carrera),
    FOREIGN KEY (pk_curso) REFERENCES Curso(id_curso),
    FOREIGN KEY (pk_ciclo) REFERENCES Ciclo(id_ciclo)
);

CREATE TABLE Profesor (
    id_profesor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR2(15) UNIQUE,
    nombre VARCHAR2(100),
    telefono VARCHAR2(20),
    email VARCHAR2(100) UNIQUE
);

CREATE TABLE Alumno (
    id_alumno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR2(15) UNIQUE,
    nombre VARCHAR2(100),
    telefono VARCHAR2(20),
    email VARCHAR2(100) UNIQUE,
    fecha_nacimiento DATE,
    pk_carrera NUMBER,
    FOREIGN KEY (pk_carrera) REFERENCES Carrera(id_carrera)
);

CREATE TABLE Grupo (
    id_grupo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pk_carrera_curso NUMBER,
    numero_grupo NUMBER,
    horario VARCHAR2(100),
    pk_profesor NUMBER,
    FOREIGN KEY (pk_carrera_curso) REFERENCES Carrera_Curso(id_carrera_curso),
    FOREIGN KEY (pk_profesor) REFERENCES Profesor(id_profesor)
);

CREATE TABLE Matricula (
    id_matricula NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pk_alumno NUMBER,
    pk_grupo NUMBER,
    nota NUMBER,
    FOREIGN KEY (pk_alumno) REFERENCES Alumno(id_alumno),
    FOREIGN KEY (pk_grupo) REFERENCES Grupo(id_grupo)
);

CREATE TABLE Usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR2(15) UNIQUE,
    clave VARCHAR2(100),
    tipo VARCHAR2(20) CHECK (tipo IN ('Administrador', 'Matriculador', 'Profesor', 'Alumno')) NOT NULL
); 
COMMIT;

--------------------------------------------------CURSOR--------------------------------------------------

CREATE OR REPLACE PACKAGE Types
AS
     TYPE ref_cursor IS REF CURSOR;
END Types;
/

-------------------------------------------------CARRERAS-------------------------------------------------

-- Insertar Carrera
CREATE OR REPLACE PROCEDURE insertarCarrera( 
                                            codigo IN Carrera.codigo%TYPE, 
                                            nombre IN Carrera.nombre%TYPE, 
                                            titulo IN Carrera.titulo%TYPE) 
AS
BEGIN
    INSERT INTO Carrera (codigo, nombre, titulo)
    VALUES (codigo, nombre, titulo);
END;
/

-- Modificar Carrera
CREATE OR REPLACE PROCEDURE modificarCarrera(id_carrerain IN Carrera.id_carrera%TYPE, 
                                            codigoin IN Carrera.codigo%TYPE, 
                                            nombrein IN Carrera.nombre%TYPE, 
                                            tituloin IN Carrera.titulo%TYPE) AS
BEGIN
    UPDATE Carrera SET  codigo = codigoin, nombre = nombrein, titulo = tituloin WHERE id_carrera = id_carrerain;
END;
/

-- Eliminar Carrera
CREATE OR REPLACE PROCEDURE eliminarCarrera(id_carrerain IN Carrera.id_carrera%TYPE) AS
BEGIN
    DELETE FROM Carrera WHERE id_carrera = id_carrerain;
END;
/

-- Listar Carreras 
CREATE OR REPLACE FUNCTION listarCarreras 
RETURN Types.ref_cursor 
AS
    carrera_cursor Types.ref_cursor;
BEGIN
    OPEN carrera_cursor FOR 
    SELECT id_carrera, codigo, nombre, titulo FROM Carrera;
    RETURN carrera_cursor;
END;
/

-- Buscar Carrera por codigo
CREATE OR REPLACE FUNCTION buscarCarreraPorCodigo(codigobuscar IN Carrera.codigo%TYPE) 
RETURN SYS_REFCURSOR AS
    carrera_cursor types.ref_cursor;
BEGIN
    OPEN carrera_cursor FOR 
    SELECT id_carrera, codigo, nombre, titulo FROM Carrera WHERE codigo=codigobuscar;
    RETURN carrera_cursor;
END;
/

-- Buscar Carrera por nombre
CREATE OR REPLACE FUNCTION buscarCarreraPorNombre(nombrebuscar IN Carrera.nombre%TYPE) 
RETURN SYS_REFCURSOR AS
    carrera_cursor types.ref_cursor;
BEGIN
    OPEN carrera_cursor FOR 
    SELECT  id_carrera, codigo, nombre, titulo FROM Carrera WHERE nombre=nombrebuscar;
    RETURN carrera_cursor;
END;
/

------------------------------------------CARRERAS_CURSO------------------------------------------
-- Insertar curso en carrera
CREATE OR REPLACE PROCEDURE insertarCursoACarrera(
    carrera_id IN Carrera.id_carrera%TYPE,
    curso_id IN Curso.id_curso%TYPE,
    ciclo_id IN Ciclo.id_ciclo%TYPE
)
AS
BEGIN
    INSERT INTO Carrera_Curso (pk_carrera, pk_curso, pk_ciclo)
    VALUES (carrera_id, curso_id, ciclo_id);
END;
/

-- Eliminar curso de carrera
CREATE OR REPLACE PROCEDURE eliminarCursoDeCarrera(
    carrera_id IN Carrera.id_carrera%TYPE,
    curso_id IN Curso.id_curso%TYPE
)
AS
BEGIN
    DELETE FROM Carrera_Curso
    WHERE pk_carrera = carrera_id AND pk_curso = curso_id;
END;
/

-- Modificar el ciclo de un curso en una carrera(cambiar el orden de un curso)
CREATE OR REPLACE PROCEDURE modificarOrdenCursoCarrera(
    p_pk_carrera IN NUMBER,
    p_pk_curso IN NUMBER,
    p_nuevo_pk_ciclo IN NUMBER
)
AS
BEGIN
    UPDATE Carrera_Curso 
    SET pk_ciclo = p_nuevo_pk_ciclo
    WHERE pk_carrera = p_pk_carrera AND pk_curso = p_pk_curso;
END;
/

-- Listar cursos por carrera y ciclo
CREATE OR REPLACE FUNCTION buscarCursosPorCarreraYCiclo(
    p_carrera_id IN Carrera.id_carrera%TYPE,
    p_ciclo_id IN Ciclo.id_ciclo%TYPE
) 
RETURN SYS_REFCURSOR AS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT 
            c.id_curso,
            c.codigo,
            c.nombre,
            c.creditos,
            c.horas_semanales,
            cc.id_carrera_curso
        FROM Curso c
        JOIN Carrera_Curso cc ON c.id_curso = cc.pk_curso
        WHERE cc.pk_carrera = p_carrera_id
          AND cc.pk_ciclo = p_ciclo_id
        ORDER BY c.codigo;

    RETURN v_cursor;
END;
/

-- Listar todas las relaciones Carrera_Curso
CREATE OR REPLACE FUNCTION listarCarreraCurso
RETURN Types.ref_cursor
AS
    cursor_out Types.ref_cursor;
BEGIN
OPEN cursor_out FOR
SELECT id_carrera_curso, pk_carrera, pk_curso, pk_ciclo
FROM Carrera_Curso;
RETURN cursor_out;
END;
/

------------------------------------------------CURSOS--------------------------------------------

-- Insertar Curso
CREATE OR REPLACE PROCEDURE insertarCurso(
                                          codigo IN Curso.codigo%TYPE, 
                                          nombre IN Curso.nombre%TYPE, 
                                          creditos IN Curso.creditos%TYPE,
                                          horas_semanales IN Curso.horas_semanales%TYPE)
AS
BEGIN
    INSERT INTO Curso (codigo, nombre, creditos, horas_semanales)
    VALUES (codigo, nombre, creditos, horas_semanales);
END;
/

-- Modificar Curso
CREATE OR REPLACE PROCEDURE modificarCurso(id_cursoin IN curso.id_curso%TYPE,
                                          codigoin IN Curso.codigo%TYPE, 
                                          nombrein IN Curso.nombre%TYPE, 
                                          creditosin IN Curso.creditos%TYPE,
                                          horas_semanalesin IN Curso.horas_semanales%TYPE)
AS
BEGIN
    UPDATE Curso SET codigo = codigoin, nombre = nombrein, creditos = creditosin, 
    horas_semanales = horas_semanalesin WHERE id_curso = id_cursoin;
END;
/

-- Eliminar Curso
CREATE OR REPLACE PROCEDURE eliminarCurso(id_cursoin IN Curso.id_curso%TYPE) AS
BEGIN
    DELETE FROM Curso WHERE id_curso = id_cursoin;
    COMMIT;
END;
/

-- Listar Cursos 
CREATE OR REPLACE FUNCTION listarCursos
RETURN Types.ref_cursor 
AS
    curso_cursor Types.ref_cursor;
BEGIN
    OPEN curso_cursor FOR 
    SELECT id_curso, codigo, nombre, creditos, horas_semanales FROM Curso;
    RETURN curso_cursor;
END;
/ 

-- Busacr Curso por nombre
CREATE OR REPLACE FUNCTION buscarCursoPorNombre(nombrebuscar IN Curso.nombre%TYPE) 
RETURN SYS_REFCURSOR AS
    curso_cursor types.ref_cursor;
BEGIN
    OPEN curso_cursor FOR 
    SELECT id_curso, codigo, nombre, creditos, horas_semanales FROM Curso WHERE nombre=nombrebuscar;
    RETURN curso_cursor;
END;
/

-- Buscar Curso por c�digo
CREATE OR REPLACE FUNCTION buscarCursoPorCodigo(codigobuscar IN Curso.codigo%TYPE) 
RETURN SYS_REFCURSOR AS
    curso_cursor types.ref_cursor;
BEGIN
    OPEN curso_cursor FOR 
    SELECT id_curso, codigo, nombre, creditos, horas_semanales FROM Curso WHERE codigo=codigobuscar;
    RETURN curso_cursor;
END;
/

-- Buscar Curso por carrera
CREATE OR REPLACE FUNCTION buscarCursosPorCarrera(
    p_carrera_id IN Carrera.id_carrera%TYPE
) 
RETURN SYS_REFCURSOR AS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT 
            c.id_curso,
            c.codigo,
            c.nombre,
            c.creditos,
            c.horas_semanales,
            cc.id_carrera_curso,
            ci.anio,
            ci.numero,
            ci.id_ciclo
        FROM Curso c
        JOIN Carrera_Curso cc ON c.id_curso = cc.pk_curso
        JOIN Ciclo ci ON cc.pk_ciclo = ci.id_ciclo
        WHERE cc.pk_carrera = p_carrera_id
        ORDER BY ci.anio, ci.numero, c.codigo;
    RETURN v_cursor;
END;
/

------------------------------------------------CICLOS--------------------------------------------

-- Insertar Ciclo
CREATE OR REPLACE PROCEDURE insertarCiclo(
                                          anio IN Ciclo.anio%TYPE, 
                                          numero IN Ciclo.numero%TYPE, 
                                          fecha_inicio IN Ciclo.fecha_inicio%TYPE, 
                                          fecha_fin IN Ciclo.fecha_fin%TYPE, 
                                          estado IN Ciclo.estado%TYPE) 
AS
BEGIN
    INSERT INTO Ciclo (anio, numero, fecha_inicio, fecha_fin, estado)
    VALUES (anio, numero, fecha_inicio, fecha_fin, estado);
    COMMIT;
END;
/

-- Modificar Ciclo
CREATE OR REPLACE PROCEDURE modificarCiclo(id_cicloin IN Ciclo.id_ciclo%TYPE,
                                           anioin IN Ciclo.anio%TYPE, 
                                           numeroin IN Ciclo.numero%TYPE, 
                                           fecha_inicioin IN Ciclo.fecha_inicio%TYPE, 
                                           fecha_finin IN Ciclo.fecha_fin%TYPE, 
                                           estadoin IN Ciclo.estado%TYPE) 
AS
BEGIN
    UPDATE Ciclo SET fecha_inicio = fecha_inicioin, fecha_fin = fecha_finin, 
    estado=estadoin, anio = anioin, numero = numeroin WHERE id_cicloin = id_ciclo;
END;
/

-- Eliminar Ciclo
CREATE OR REPLACE PROCEDURE eliminarCiclo(id_cicloin IN Ciclo.id_ciclo%TYPE) 
AS
BEGIN
    DELETE FROM Ciclo WHERE id_ciclo = id_cicloin;
    COMMIT;
END;
/

-- Listar Ciclos 
CREATE OR REPLACE FUNCTION listarCiclos
RETURN Types.ref_cursor 
AS
    ciclo_cursor Types.ref_cursor;
BEGIN
    OPEN ciclo_cursor FOR 
    SELECT id_ciclo, anio, numero, fecha_inicio, fecha_fin, estado FROM Ciclo;
    RETURN ciclo_cursor;
END;
/

-- Consultar Ciclos por a�o
CREATE OR REPLACE FUNCTION buscarCicloPorAnnio(annioBuscar IN Ciclo.anio%TYPE) 
RETURN SYS_REFCURSOR AS
    ciclo_cursor types.ref_cursor;
BEGIN
    OPEN ciclo_cursor FOR 
    SELECT id_ciclo, anio, numero, fecha_inicio, fecha_fin, estado FROM Ciclo 
    WHERE anio=annioBuscar;
    RETURN ciclo_cursor;
END;
/

-- Activar ciclo
CREATE OR REPLACE PROCEDURE activarCiclo(id_cicloin IN Ciclo.id_ciclo%TYPE) 
AS
BEGIN
    UPDATE Ciclo SET estado='Inactivo';
    UPDATE Ciclo SET estado='Activo' WHERE id_ciclo = id_cicloin;
END;
/

------------------------------------------------PROFESORES--------------------------------------------

-- Insertar Profesor
CREATE OR REPLACE PROCEDURE insertarProfesor(
                                            cedula IN Profesor.cedula%TYPE, 
                                            nombre IN Profesor.nombre%TYPE, 
                                            telefono IN Profesor.telefono%TYPE , 
                                            email IN Profesor.email%TYPE) 
AS
BEGIN
    INSERT INTO Profesor  (cedula, nombre, telefono, email)
    VALUES (cedula, nombre, telefono, email);
END;
/

-- Modificar Profesor
CREATE OR REPLACE PROCEDURE modificarProfesor(id_profesorin IN Profesor.id_profesor%TYPE,
                                              cedulain IN Profesor.cedula%TYPE, 
                                              nombrein IN Profesor.nombre%TYPE, 
                                              telefonoin IN Profesor.telefono%TYPE , 
                                              emailin IN Profesor.email%TYPE) 
AS
BEGIN
    UPDATE Profesor SET cedula = cedulain, nombre = nombrein, telefono = telefonoin, email = emailin WHERE id_profesor = id_profesorin;
END;
/

-- Eliminar Profesor
CREATE OR REPLACE PROCEDURE eliminarProfesor(id_profesorin IN Profesor.id_profesor%TYPE) AS
BEGIN
    DELETE FROM Profesor WHERE id_profesor = id_profesorin;

END;
/

-- Listar Profesores 
CREATE OR REPLACE FUNCTION listarProfesores
RETURN Types.ref_cursor 
AS
    profesor_cursor Types.ref_cursor;
BEGIN
    OPEN profesor_cursor FOR 
    SELECT id_profesor, cedula, nombre, telefono, email FROM Profesor;
    RETURN profesor_cursor;
END;
/

-- Buscar Profesor por cedula
CREATE OR REPLACE FUNCTION buscarProfesorPorCedula(cedulabuscar IN Profesor.cedula%TYPE) 
RETURN SYS_REFCURSOR AS
    profesor_cursor types.ref_cursor;
BEGIN
    OPEN profesor_cursor FOR 
    SELECT id_profesor, cedula, nombre, telefono, email FROM Profesor WHERE cedula=cedulabuscar;
    RETURN profesor_cursor;
END;
/

-- Buscar Profesor por nombre
CREATE OR REPLACE FUNCTION buscarProfesorPorNombre(nombrebuscar IN Profesor.nombre%TYPE) 
RETURN SYS_REFCURSOR AS
    profesor_cursor types.ref_cursor;
BEGIN
    OPEN profesor_cursor FOR 
    SELECT id_profesor, cedula, nombre, telefono, email FROM Profesor WHERE nombre=nombrebuscar;
    RETURN profesor_cursor;
END;
/

------------------------------------------------ALUMNOS--------------------------------------------

-- Insertar Alumno
CREATE OR REPLACE PROCEDURE insertarAlumno(
                                            cedula Alumno.cedula%TYPE, 
                                            nombre Alumno.nombre%TYPE, 
                                            telefono Alumno.telefono%TYPE, 
                                            email Alumno.email%TYPE, 
                                            fecha_nacimiento Alumno.fecha_nacimiento%TYPE, 
                                            pk_carrera Alumno.pk_carrera%TYPE) 
AS
BEGIN
    INSERT INTO Alumno (cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera)
    VALUES (cedula, nombre, telefono, email,fecha_nacimiento,pk_carrera);
    COMMIT;
END;
/

-- Modificar Alumno
CREATE OR REPLACE PROCEDURE modificarAlumno(id_alumnoin IN Alumno.id_alumno%TYPE,
                                            cedulain IN Alumno.cedula%TYPE, 
                                            nombrein IN Alumno.nombre%TYPE, 
                                            telefonoin IN Alumno.telefono%TYPE, 
                                            emailin IN Alumno.email%TYPE, 
                                            fecha_nacimientoin IN Alumno.fecha_nacimiento%TYPE, 
                                            pk_carrerain IN Alumno.pk_carrera%TYPE) AS
BEGIN
    UPDATE Alumno SET cedula = cedulain, nombre = nombrein, telefono = telefonoin, email = emailin, fecha_nacimiento = fecha_Nacimientoin,
                        pk_carrera = pk_carrerain WHERE id_alumno = id_alumnoin;
END;
/

-- Eliminar Alumno
CREATE OR REPLACE PROCEDURE eliminarAlumno(id_alumnoin IN Alumno.id_alumno%TYPE) 
AS
BEGIN
    DELETE FROM Alumno WHERE id_alumno = id_alumnoin;
END;
/

-- Listar Alumnos 
CREATE OR REPLACE FUNCTION listarAlumnos
RETURN Types.ref_cursor 
AS
    alumno_cursor Types.ref_cursor;
BEGIN
OPEN alumno_cursor FOR
SELECT id_alumno, cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera FROM Alumno;
RETURN alumno_cursor;
END;
/

-- Buscar Alumno por cedula
CREATE OR REPLACE FUNCTION buscarAlumnoPorCedula(cedulabuscar IN Alumno.cedula%TYPE)
RETURN SYS_REFCURSOR AS
    alumno_cursor types.ref_cursor;
BEGIN
OPEN alumno_cursor FOR
SELECT id_alumno, cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera FROM Alumno WHERE cedula=cedulabuscar;
RETURN alumno_cursor;
END;
/

-- Buscar Alumno por nombre
CREATE OR REPLACE FUNCTION buscarAlumnoPorNombre(nombrebuscar IN Alumno.nombre%TYPE)
RETURN SYS_REFCURSOR AS
    alumno_cursor types.ref_cursor;
BEGIN
OPEN alumno_cursor FOR
SELECT id_alumno, cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera FROM Alumno WHERE nombre=nombrebuscar;
RETURN alumno_cursor;
END;
/

-- Buscar Alumno por carrera
CREATE OR REPLACE FUNCTION buscarAlumnosPorCarrera(carrerabuscar IN Alumno.pk_carrera%TYPE)
RETURN SYS_REFCURSOR AS
    alumno_cursor types.ref_cursor;
BEGIN
OPEN alumno_cursor FOR
SELECT id_alumno, cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera FROM Alumno WHERE pk_carrera=carrerabuscar;
RETURN alumno_cursor;
END;
/

COMMIT;

------------------------------------------------GRUPOS--------------------------------------------

-- Insertar Grupo
CREATE OR REPLACE PROCEDURE insertarGrupo(pk_carrera_curso IN Grupo.pk_carrera_curso%TYPE,
                                          numero_grupo IN Grupo.numero_grupo%TYPE, 
                                          horario IN Grupo.horario%TYPE, 
                                          pk_profesor IN Grupo.pk_profesor%TYPE) 
AS
BEGIN
    INSERT INTO Grupo(pk_carrera_curso, numero_grupo, horario, pk_profesor)
    VALUES (pk_carrera_curso, numero_grupo, horario, pk_profesor);
END;
/

-- Modificar Grupo
CREATE OR REPLACE PROCEDURE modificarGrupo(id_grupoin Grupo.id_grupo%TYPE, 
                                          pk_carrera_cursoin Grupo.pk_carrera_curso%TYPE,
                                          numero_grupoin Grupo.numero_grupo%TYPE, 
                                          horarioin Grupo.horario%TYPE, 
                                          pk_profesorin Grupo.pk_profesor%TYPE) 
AS
BEGIN
    UPDATE Grupo SET  pk_carrera_curso = pk_carrera_cursoin,
                      numero_grupo = numero_grupoin, 
                      horario =  horarioin, 
                      pk_profesor = pk_profesorin WHERE id_grupo = id_grupoin;
END;
/

-- Eliminar Grupo
CREATE OR REPLACE PROCEDURE eliminarGrupo(id_grupoin IN Grupo.id_grupo%TYPE) 
AS
BEGIN
    DELETE FROM Grupo WHERE id_grupo = id_grupoin;
END;
/

-- Listar Grupos
CREATE OR REPLACE FUNCTION listarGrupos
RETURN Types.ref_cursor 
AS
    grupo_cursor Types.ref_cursor;
BEGIN
    OPEN grupo_cursor FOR 
    SELECT id_grupo, pk_carrera_curso, numero_grupo, horario, pk_profesor FROM Grupo;
    RETURN grupo_cursor;
END;
/

-- Buscar grupos por curso(carrera_curso)
CREATE OR REPLACE FUNCTION buscarGruposPorCarreraCurso(
    p_id_carrera IN Carrera.id_carrera%TYPE,
    p_id_curso IN Curso.id_curso%TYPE
) RETURN SYS_REFCURSOR AS
    grupos_cursor Types.ref_cursor;
BEGIN
    OPEN grupos_cursor FOR
    SELECT g.id_grupo,
           g.pk_carrera_curso,
           g.numero_grupo,
           g.horario,
           p.id_profesor AS pk_profesor,
           p.nombre AS nombre_profesor
    FROM Grupo g
    JOIN Profesor p ON g.pk_profesor = p.id_profesor
    JOIN Carrera_Curso cc ON g.pk_carrera_curso = cc.id_carrera_curso
    WHERE cc.pk_carrera = p_id_carrera
      AND cc.pk_curso = p_id_curso;
    
    RETURN grupos_cursor;
END;
/

------------------------------------------------MATRICULAS--------------------------------------------

-- Insertar Matricula
CREATE OR REPLACE PROCEDURE insertarMatricula(pk_alumno IN Matricula.pk_alumno%TYPE, pk_grupo IN Matricula.pk_grupo%TYPE) 
AS
BEGIN
    INSERT INTO Matricula (pk_alumno,pk_grupo)
    VALUES (pk_alumno,pk_grupo);
END;
/

-- Modificar Matricula
CREATE OR REPLACE PROCEDURE modificarMatricula(id_matriculain Matricula.id_matricula%TYPE, 
                                              pk_alumnoin Matricula.pk_alumno%TYPE, 
                                              pk_grupoin Matricula.pk_grupo%TYPE, 
                                              notain Matricula.nota%TYPE) 
AS
BEGIN
    UPDATE Matricula SET pk_alumno = pk_alumnoin,  pk_grupo = pk_grupoin, nota = notain WHERE id_matricula = id_matriculain;
END;
/

-- Eliminar Matricula
CREATE OR REPLACE PROCEDURE eliminarMatricula(id_matriculain IN Matricula.id_matricula%TYPE) 
AS
BEGIN
    DELETE FROM Matricula WHERE id_matricula = id_matriculain;
END;
/

-- Listar Matricular Por Alumno
CREATE OR REPLACE FUNCTION listarMatriculasPorAlumno(
    p_id_alumno IN Alumno.id_alumno%TYPE
) RETURN SYS_REFCURSOR
AS
    matriculas_cursor Types.ref_cursor;
BEGIN
    OPEN matriculas_cursor FOR
        SELECT 
            m.id_matricula,
            m.nota,
            g.numero_grupo,
            g.horario,
            c.codigo AS codigo_carrera,
            c.nombre AS nombre_carrera,
            cu.codigo AS codigo_curso,
            cu.nombre AS nombre_curso,
            p.nombre AS nombre_profesor,
            p.cedula AS cedula_profesor
        FROM Matricula m
        JOIN Grupo g ON m.pk_grupo = g.id_grupo
        JOIN Profesor p ON g.pk_profesor = p.id_profesor
        JOIN Carrera_Curso cc ON g.pk_carrera_curso = cc.id_carrera_curso
        JOIN Carrera c ON cc.pk_carrera = c.id_carrera
        JOIN Curso cu ON cc.pk_curso = cu.id_curso
        WHERE m.pk_alumno = p_id_alumno;
    
    RETURN matriculas_cursor;
END;
/

-- Listar Matricular Por Alumno Y Ciclo
CREATE OR REPLACE FUNCTION listarMatriculasPorAlumnoYCiclo(
    p_id_alumno IN Alumno.id_alumno%TYPE,
    p_id_ciclo  IN Ciclo.id_ciclo%TYPE
) RETURN SYS_REFCURSOR
AS
    resultado SYS_REFCURSOR;
BEGIN
    OPEN resultado FOR
        SELECT 
            m.id_matricula,
            m.nota,
            g.numero_grupo,
            g.horario,
            c.codigo AS codigo_carrera,
            c.nombre AS nombre_carrera,
            cu.codigo AS codigo_curso,
            cu.nombre AS nombre_curso,
            p.nombre AS nombre_profesor,
            p.cedula AS cedula_profesor
        FROM Matricula m
        JOIN Grupo g ON m.pk_grupo = g.id_grupo
        JOIN Profesor p ON g.pk_profesor = p.id_profesor
        JOIN Carrera_Curso cc ON g.pk_carrera_curso = cc.id_carrera_curso
        JOIN Carrera c ON cc.pk_carrera = c.id_carrera
        JOIN Curso cu ON cc.pk_curso = cu.id_curso
        JOIN Ciclo ci ON cc.pk_ciclo = ci.id_ciclo
        WHERE m.pk_alumno = p_id_alumno
          AND ci.id_ciclo = p_id_ciclo;
    
    RETURN resultado;
END;
/


------------------------------------------------USUARIOS--------------------------------------------

-- Insertar Usuario
CREATE OR REPLACE PROCEDURE insertarUsuario(cedula IN Usuario.cedula%TYPE, clave IN Usuario.clave%TYPE, tipo IN Usuario.tipo%TYPE) 
AS
BEGIN
    INSERT INTO Usuario (cedula, clave, tipo)
    VALUES (cedula, clave, tipo);
END;
/

-- Modificar Usuario
CREATE OR REPLACE PROCEDURE modificarUsuario(id_usuarioin IN Usuario.id_usuario%TYPE,
                                            cedulain IN Usuario.cedula%TYPE,
                                            tipoin IN Usuario.tipo%TYPE) AS
BEGIN
    UPDATE Usuario SET cedula = cedulain, tipo = tipoin WHERE id_usuario = id_usuarioin;
END;
/

-- Eliminar Usuario
CREATE OR REPLACE PROCEDURE eliminarUsuario(id_usuarioin IN Usuario.id_usuario%TYPE) AS
BEGIN
    DELETE FROM Usuario WHERE id_usuario = id_usuarioin;
END;
/

-- Listar Usuarios 
CREATE OR REPLACE FUNCTION listarUsuarios
RETURN Types.ref_cursor 
AS
    usuario_cursor Types.ref_cursor;
BEGIN
    OPEN usuario_cursor FOR 
    SELECT id_usuario, cedula, tipo FROM Usuario;
    RETURN usuario_cursor;
END;
/

-- Consultar Usuario por cedula
CREATE OR REPLACE FUNCTION buscarUsuarioPorCedula(cedulabuscar IN Usuario.cedula%TYPE) 
RETURN SYS_REFCURSOR AS
    usuario_cursor types.ref_cursor;
BEGIN
    OPEN usuario_cursor FOR 
    SELECT id_usuario, cedula, tipo FROM Usuario WHERE cedula=cedulabuscar;
    RETURN usuario_cursor;
END;
/

-- Login de un Usuario
CREATE OR REPLACE PROCEDURE loginUsuario(
    cedulain IN Usuario.cedula%TYPE,
    clavein IN Usuario.clave%TYPE,
    usuario_cursor OUT Types.ref_cursor
)
AS
BEGIN
    OPEN usuario_cursor FOR
    SELECT id_usuario, cedula, tipo
    FROM Usuario
    WHERE cedula = cedulain AND clave = clavein;
END;
/

----------------------------------------------------------------------------------------------------------
-- INSERCIÓN DE DATOS DE PRUEBA
----------------------------------------------------------------------------------------------------------

-- CARRERAS
INSERT INTO Carrera (codigo, nombre, titulo) VALUES ('INF01', 'Ingeniería en Informática', 'Bachiller en Ingeniería en Informática');
INSERT INTO Carrera (codigo, nombre, titulo) VALUES ('ADM01', 'Administración de Empresas', 'Bachiller en Administración');
INSERT INTO Carrera (codigo, nombre, titulo) VALUES ('TUR01', 'Gestión Turística', 'Bachiller en Gestión Turística');

-- CURSOS
INSERT INTO Curso (codigo, nombre, creditos, horas_semanales) VALUES ('INF101', 'Programación I', 4, 6);
INSERT INTO Curso (codigo, nombre, creditos, horas_semanales) VALUES ('INF201', 'Estructuras de Datos', 4, 5);
INSERT INTO Curso (codigo, nombre, creditos, horas_semanales) VALUES ('ADM101', 'Contabilidad Básica', 3, 4);
INSERT INTO Curso (codigo, nombre, creditos, horas_semanales) VALUES ('ADM201', 'Gestión Financiera', 4, 5);
INSERT INTO Curso (codigo, nombre, creditos, horas_semanales) VALUES ('TUR101', 'Introducción al Turismo', 3, 3);
INSERT INTO Curso (codigo, nombre, creditos, horas_semanales) VALUES ('TUR201', 'Turismo Sostenible', 4, 4);

-- CICLOS
INSERT INTO Ciclo (anio, numero, fecha_inicio, fecha_fin, estado)
VALUES (2025, 1, TO_DATE('2025-02-01', 'YYYY-MM-DD'), TO_DATE('2025-06-01', 'YYYY-MM-DD'), 'Activo');
INSERT INTO Ciclo (anio, numero, fecha_inicio, fecha_fin, estado)
VALUES (2025, 2, TO_DATE('2025-07-01', 'YYYY-MM-DD'), TO_DATE('2025-11-01', 'YYYY-MM-DD'), 'Inactivo');

-- CARRERA CURSO
INSERT INTO Carrera_Curso (pk_carrera, pk_curso, pk_ciclo) VALUES (1, 1, 1);
INSERT INTO Carrera_Curso (pk_carrera, pk_curso, pk_ciclo) VALUES (1, 2, 2);
INSERT INTO Carrera_Curso (pk_carrera, pk_curso, pk_ciclo) VALUES (2, 3, 1);
INSERT INTO Carrera_Curso (pk_carrera, pk_curso, pk_ciclo) VALUES (2, 4, 2);
INSERT INTO Carrera_Curso (pk_carrera, pk_curso, pk_ciclo) VALUES (3, 5, 1);
INSERT INTO Carrera_Curso (pk_carrera, pk_curso, pk_ciclo) VALUES (3, 6, 2);

-- PROFESORES
INSERT INTO Profesor (cedula, nombre, telefono, email) VALUES ('100100100', 'Carlos Rojas', '88888888', 'crojas@uni.edu');
INSERT INTO Profesor (cedula, nombre, telefono, email) VALUES ('200200200', 'María López', '87777777', 'mlopez@uni.edu');
INSERT INTO Profesor (cedula, nombre, telefono, email) VALUES ('300300300', 'Luis Jiménez', '86666666', 'ljimenez@uni.edu');
INSERT INTO Profesor (cedula, nombre, telefono, email) VALUES ('400400400', 'Ana Salas', '85555555', 'asalas@uni.edu');

-- ALUMNOS
INSERT INTO Alumno (cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera)
VALUES ('111111111', 'Laura Fernández', '85001234', 'laura@correo.com', TO_DATE('2000-03-15','YYYY-MM-DD'), 1);
INSERT INTO Alumno (cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera)
VALUES ('222222222', 'José Ramírez', '84005678', 'jose@correo.com', TO_DATE('1999-11-20','YYYY-MM-DD'), 1);
INSERT INTO Alumno (cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera)
VALUES ('333333333', 'Ana Rodríguez', '87007890', 'ana@correo.com', TO_DATE('2001-06-10','YYYY-MM-DD'), 2);
INSERT INTO Alumno (cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera)
VALUES ('444444444', 'David Castro', '83009876', 'david@correo.com', TO_DATE('2000-12-25','YYYY-MM-DD'), 2);
INSERT INTO Alumno (cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera)
VALUES ('555555555', 'Sofía Vega', '89006789', 'sofia@correo.com', TO_DATE('2002-08-30','YYYY-MM-DD'), 3);
INSERT INTO Alumno (cedula, nombre, telefono, email, fecha_nacimiento, pk_carrera)
VALUES ('666666666', 'Andrés Mora', '82001234', 'andres@correo.com', TO_DATE('1998-04-17','YYYY-MM-DD'), 3);

-- GRUPOS
INSERT INTO Grupo (pk_carrera_curso, numero_grupo, horario, pk_profesor) VALUES (1, 1, 'Lunes 8:00-10:00', 1);
INSERT INTO Grupo (pk_carrera_curso, numero_grupo, horario, pk_profesor) VALUES (2, 1, 'Miércoles 10:00-12:00', 1);
INSERT INTO Grupo (pk_carrera_curso, numero_grupo, horario, pk_profesor) VALUES (3, 1, 'Martes 9:00-11:00', 2);
INSERT INTO Grupo (pk_carrera_curso, numero_grupo, horario, pk_profesor) VALUES (5, 1, 'Jueves 2:00-4:00', 4);

-- MATRICULAS
INSERT INTO Matricula (pk_alumno, pk_grupo, nota) VALUES (1, 1, 85);
INSERT INTO Matricula (pk_alumno, pk_grupo, nota) VALUES (2, 2, 90);
INSERT INTO Matricula (pk_alumno, pk_grupo, nota) VALUES (3, 3, 78);
INSERT INTO Matricula (pk_alumno, pk_grupo, nota) VALUES (4, 3, 88);
INSERT INTO Matricula (pk_alumno, pk_grupo, nota) VALUES (5, 4, 92);
INSERT INTO Matricula (pk_alumno, pk_grupo, nota) VALUES (6, 4, 74);
INSERT INTO Matricula (pk_alumno, pk_grupo, nota) VALUES (2, 1, 81);
INSERT INTO Matricula (pk_alumno, pk_grupo, nota) VALUES (1, 2, 87);

-- USUARIOS
INSERT INTO Usuario (cedula, clave, tipo) VALUES ('100100100', 'admin123', 'Administrador');
INSERT INTO Usuario (cedula, clave, tipo) VALUES ('200200200', 'matri456', 'Matriculador');
INSERT INTO Usuario (cedula, clave, tipo) VALUES ('300300300', 'prof789', 'Profesor');
INSERT INTO Usuario (cedula, clave, tipo) VALUES ('111111111', 'alumno1', 'Alumno');
INSERT INTO Usuario (cedula, clave, tipo) VALUES ('333333333', 'alumno2', 'Alumno');
INSERT INTO Usuario (cedula, clave, tipo) VALUES ('555555555', 'alumno3', 'Alumno');

COMMIT;

----------------------------------------------------------------------------------------------------------
-- PRUEBAS
----------------------------------------------------------------------------------------------------------

-- Visualización general
SELECT * FROM CARRERA;
SELECT * FROM CURSO;
SELECT * FROM CICLO;
SELECT * FROM CARRERA_CURSO;
SELECT * FROM PROFESOR;
SELECT * FROM ALUMNO;
SELECT * FROM GRUPO;
SELECT * FROM MATRICULA;
SELECT * FROM USUARIO;

-- Verificar relaciones entre entidades (JOINs)

-- Alumnos con su carrera
SELECT a.nombre AS alumno, c.nombre AS carrera
FROM ALUMNO a
         JOIN CARRERA c ON a.pk_carrera = c.id_carrera;

-- Matrículas con detalle completo: alumno, carrera, curso, nota
SELECT
    a.nombre AS alumno,
    c.nombre AS carrera,
    cu.nombre AS curso,
    m.nota
FROM MATRICULA m
         JOIN ALUMNO a ON m.pk_alumno = a.id_alumno
         JOIN GRUPO g ON m.pk_grupo = g.id_grupo
         JOIN CARRERA_CURSO cc ON g.pk_carrera_curso = cc.id_carrera_curso
         JOIN CURSO cu ON cc.pk_curso = cu.id_curso
         JOIN CARRERA c ON a.pk_carrera = c.id_carrera;

-- Profesores y los grupos que imparten
SELECT
    p.nombre AS profesor,
    cu.nombre AS curso,
    g.numero_grupo,
    g.horario
FROM PROFESOR p
         JOIN GRUPO g ON p.id_profesor = g.pk_profesor
         JOIN CARRERA_CURSO cc ON g.pk_carrera_curso = cc.id_carrera_curso
         JOIN CURSO cu ON cc.pk_curso = cu.id_curso;

-- Ver procedimientos y funciones compilados
SELECT OBJECT_NAME, PROCEDURE_NAME, OBJECT_TYPE
FROM USER_PROCEDURES
WHERE OBJECT_TYPE IN ('FUNCTION', 'PROCEDURE')
ORDER BY OBJECT_NAME, PROCEDURE_NAME;
